// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: complete_singlefile.sql

package auctionLot

import (
	"context"

	"github.com/google/uuid"
)

const commitSingleFileUpload = `-- name: CommitSingleFileUpload :exec
update image_blob_upload_attempts set upload_state='committed',verified=true where upload_type='singleUpload' and storage_key= $1::uuid and upload_state='pending'
`

func (q *Queries) CommitSingleFileUpload(ctx context.Context, storageKey uuid.UUID) error {
	_, err := q.db.Exec(ctx, commitSingleFileUpload, storageKey)
	return err
}
