// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: complete_multipart.sql

package auctionLot

import (
	"context"

	"github.com/google/uuid"
)

const commitMultiPartUpload = `-- name: CommitMultiPartUpload :exec
update image_blob_upload_attempts set upload_state='committed' where upload_type='multiUpload' and storage_key= $1::uuid and upload_state='pending'
`

func (q *Queries) CommitMultiPartUpload(ctx context.Context, storageKey uuid.UUID) error {
	_, err := q.db.Exec(ctx, commitMultiPartUpload, storageKey)
	return err
}
